/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yourcompany.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.yourcompany.struts.form.ComposeForm;

/** 
 * MyEclipse Struts
 * Creation date: 03-29-2013
 * 
 * XDoclet definition:
 * @struts.action path="/compose" name="composeForm" input="/form/compose.jsp" scope="request" validate="true"
 */
public class ComposeAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	 public ActionForward execute(ActionMapping mapping, ActionForm form,
	            HttpServletRequest request, HttpServletResponse response)
	            throws Exception {
		ComposeForm composeForm = (ComposeForm) form;// TODO Auto-generated method stub
		
		HttpSession sen = request.getSession();
		String _sender = (String) sen.getAttribute("Email");
		String _receiver = composeForm.getReceiver();
		String _subject = composeForm.getSubject();
		String _msg = composeForm.getMsg();
		//String _dat = composeForm.getDat();
		
		int i=SendMessage.sendMsg(_sender, _receiver, _subject, _msg);
		if(i>0){
			
	            //int j=parse.Integer(reciever);
				//if(j>0){
		
			System.out.print("Message Sucessfully Sent");
			//RequestDispatcher rd=request.getRequestDispatcher("home.jsp");
			//rd.include(request, response);
			return mapping.findForward("success");
		}
		else{
			System.out.print("Sorry,Message was not sent");
			//RequestDispatcher rd=request.getRequestDispatcher("compose.jsp");
			//rd.include(request, response);
			return mapping.findForward("failure");
		}
		//return null;
	}
	
	 
	
}