/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yourcompany.struts.action;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Random;

import javax.activation.MailcapCommandMap;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import com.yourcompany.struts.form.ForgotpassForm;

/** 
 * MyEclipse Struts
 * Creation date: 03-31-2013
 * 
 * XDoclet definition:
 * @struts.action path="/forgotpass" name="forgotpassForm" input="/form/forgotpass.jsp" scope="request" validate="true"
 */
public class ForgotpassAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		ForgotpassForm forgotpassForm = (ForgotpassForm) form;// TODO Auto-generated method stub
	
		String em = forgotpassForm.getEmail_ID();
		
		
		PreparedStatement stmt = null;
		ResultSet rs = null;
		String qry = "SELECT altemail,random From mailuser where email=? ";
		Connection con=GetCon.getCon();
		PreparedStatement ps;   
		try{
		  		
		         //con = DriverManager.getConnection("jdbc:mysql://localhost:3306/test");
		         stmt = con.prepareStatement(qry);
		         
				stmt.setString(1, em);
		         rs =  stmt.executeQuery();
		         while (rs.next()) {
		               String raxit = rs.getString("altemail");
		               String code1 = rs.getString("random");
		               //out.println(raxit);
		               HttpSession sen = request.getSession();
		               sen.setAttribute("AltEmail",raxit);
		               sen.setAttribute("Code", code1);
		         }
		         }
		catch (SQLException e) {
					
					e.printStackTrace();
				}

		HttpSession sen = request.getSession();
		String to = (String)sen.getAttribute("AltEmail");
		String code = (String)sen.getAttribute("Code");
		//int code = parse
		//System.out.println(to);
		
		 
		    Mail m = new Mail();
		
		m.setTo(to);
		m.setSmtpServ("smtp.gmail.com");
		m.setSubject("reSetPassword");
		//String code = (String) sen.getAttribute("Code");
		m.setMessage("http://raxit:8080/MailService/form/resetPass.jsp?"+code );
		to = m.getTo();
		m.setFrom("SecureInfotech");
		
		int result;


		result = m.sendMail();


		if(result == 0)
		{
		   
		 System.out.println(" Mail Successfully Sent to "+to);
		 return mapping.findForward("success");
		}

		else
		{
		 
		   System.out.println(" Mail NOT Sent to "+to);

		}
		   
		
			System.out.println("mail sent"+ to);
			
			request.getSession().setAttribute("emailInvalid",to);
			
			return mapping.findForward("failure");

		
		
		
		     //return null;
}
	
}